import { chromium } from "playwright";
const S = process.argv[2] ?? "screenshots";
import fs from "node:fs"; fs.mkdirSync(S, { recursive: true });
const b = await chromium.launch(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {});
const page = await b.newPage({ viewport: { width: 1280, height: 360 } });
page.on("pageerror", (e) => console.log("PAGEERROR", e.message));
page.on("console", (m) => { if (m.type() === "error") console.log("CONSOLE", m.text()); });
await page.goto("http://localhost:8787/");
await page.waitForTimeout(1500);
await page.screenshot({ path: `${S}/display-lanes.png` });
await fetch("http://localhost:8787/api/moment", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ kind: "confetti", title: "HOU SCORE!", subtitle: "NYY 1 - HOU 4", color: "#eb6e1f", color2: "#ffffff", duration: 6000, priority: 90 }) });
await page.waitForTimeout(2200);
await page.screenshot({ path: `${S}/display-moment.png` });
const admin = await b.newPage({ viewport: { width: 1280, height: 1100 } });
admin.on("pageerror", (e) => console.log("ADMIN PAGEERROR", e.message));
await admin.goto("http://localhost:8787/admin");
await admin.waitForTimeout(1500);
await admin.screenshot({ path: `${S}/admin.png`, fullPage: true });
await b.close();
console.log("shots done");
